### ISSUE TITLE
Package unmaintained

### ISSUE THREAD

**Issue by jtniehof** [jtniehof/pam_shield#16]
As might be obvious, this package is currently unmaintained. There was some interest in taking over maintenance a year and a half ago but that party disappeared. If someone is interested in maintaining pam-shield, I am happy to point to their repo.

**Comment by h0tw1r3** [comment]
@jtniehof I'm available to take over maintenance.

**Comment by jtniehof** [comment]
@h0tw1r3 , that would be great. Here's what I think would make sense for a transition:

- Can you enable issues on your fork so people can open them up there? (And then ultimately we can port existing from here).
- Update the readme to describe your involvement
- Cut a release

Then I can update things here to point to you (probably by pulling from your branch and then locking up this repo.)

@walterdejong , do you have thoughts?

**Comment by h0tw1r3** [comment]
@jtniehof should be all set.

**Comment by walterdejong** [comment]
I have no issues.
Thanks to all for your work and taking care of pam_shield.

**Comment by jtniehof** [comment]
Excellent, thank you! You may also wish to edit the repository settings (gear icon next to the About) and change the website to your repo.
